name: Backend CI/CD
on:
  push:
    branches:
      - master
    paths:
      - /backend/**
  pull_request:
    branches:
      - master
    paths:
      - backend/**
env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./backend
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
        working-directory: ./backend
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always() && github.event_name != 'workflow_dispatch'
        with:
          name: .NET Tests
          path: backend/**/TestResults/*.trx
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}
  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    # Remove the if condition at job level - act will handle this
    steps:
      - uses: actions/checkout@v3
      - name: Check if running in act
        id: check-act
        run: |
          if [[ -n "$ACT" ]]; then
            echo "::set-output name=is-act::true"
          else
            echo "::set-output name=is-act::false"
          fi
      - name: Log in to GitHub Container Registry
        if: steps.check-act.outputs.is-act != 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: steps.check-act.outputs.is-act != 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}